export enum ImageKey {
    BackGround = 1,
    Coins = 2,
    Diamond = 3,
    DisplayPanelBK = 4,
    Gold = 5,
    LedsSafeDial = 6,
    Marker = 7,
    Notes = 8,
    Ring = 9,
    SafeDialMiniGame = 10,
    SafeMini = 11,
    SafeOpenMini = 12,
    ScreenSafeBk = 14,
    ScreenSafeMini = 15,
    ScreenSafeWin = 16,
    SparkSafe = 17,
    StarGreen = 18,
    Star = 19,
    SupportSafeDial = 20,
    SpinTextSafe = 21,
};
